# Generated by Django 3.2.7 on 2021-11-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono_empleado',
            field=models.BigIntegerField(default='0000000000'),
        ),
    ]
