# Generated by Django 3.2.7 on 2021-11-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_alter_customuser_telefono_empleado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Almacen',
            new_name='Movimientos_Almacen',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cargo_empleado',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordenes_salida_materiaprima',
            name='cantidad_entregada',
            field=models.IntegerField(),
        ),
    ]
