# Generated by Django 3.2.7 on 2021-11-24 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20211123_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_pedido_materiaprima',
            name='codigo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.materia_prima'),
        ),
    ]
