# Generated by Django 3.2.7 on 2021-11-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_auto_20211119_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratistas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='materia_prima',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movimientos_almacen',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ordenes_pedido_materiaprima',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ordenes_salida_materiaprima',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='id',
        ),
        migrations.AlterField(
            model_name='contratistas',
            name='codigo_contratista',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cargo_empleado',
            field=models.CharField(choices=[('DG', 'Director General'), ('DO', 'Director Operacional'), ('AL', 'Almacenista'), ('PR', 'Proveedor'), ('CO', 'Contratista'), ('NA', 'No Asignado')], default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codigo_empleado',
            field=models.BigIntegerField(default='0000000000'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='codigo_factura',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='codigo_producto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimientos_almacen',
            name='cod_movimiento',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordenes_pedido_materiaprima',
            name='codigo_orden_pedido',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordenes_salida_materiaprima',
            name='codigo_orden_salida',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='codigo_proveedor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='maneja_credito',
            field=models.CharField(choices=[('Si', 'Si Maneja Crédito'), ('No', 'No Ofrece Crédito')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='codigo_proyecto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
