# Generated by Django 3.2.7 on 2021-11-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_auto_20211125_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo_empleado',
            field=models.CharField(choices=[('Gerente General', 'Director General'), ('Director Operacional', 'Director Operacional'), ('Almacenista', 'Almacenista'), ('Contratista', 'Contratista'), ('NA', 'No Asignado')], default='NA', max_length=50),
        ),
    ]
