# Generated by Django 3.2.7 on 2021-11-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_alter_ordenes_pedido_materiaprima_codigo_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='codigo_empleado',
            new_name='identificacion',
        ),
    ]
