# Generated by Django 3.2.7 on 2021-11-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_auto_20211119_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos_almacen',
            name='tipo_movimiento',
            field=models.CharField(choices=[('En', 'Entrada'), ('Sa', 'Salida'), ('Na', 'Sin Asignar Aún')], default='Na', max_length=8),
        ),
    ]
