# Generated by Django 3.2.7 on 2021-11-22 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_alter_movimientos_almacen_tipo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratistas',
            name='proyecto_asignacion',
            field=models.ForeignKey(default='00000000', on_delete=django.db.models.deletion.CASCADE, to='inventarios.proyectos'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='estado_proyecto',
            field=models.CharField(choices=[('Act', 'Activo'), ('Ter', 'Terminado'), ('Na', 'No Asignado')], default='No', max_length=12),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='empleado_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
