# Generated by Django 3.2.7 on 2021-11-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_auto_20211123_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(default='ejemplo@ejemplo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contratistas',
            name='correo_contratista',
            field=models.EmailField(default='ejemplo@ejemplo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='correo_empleado',
            field=models.EmailField(default='ejemplo@ejemplo.com', max_length=254),
        ),
    ]
