# Generated by Django 3.2.7 on 2021-11-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_auto_20211123_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia_prima',
            name='Proveedores_cod_proveedor',
        ),
        migrations.AddField(
            model_name='materia_prima',
            name='Proveedores_cod_proveedor',
            field=models.ManyToManyField(to='inventarios.Proveedores'),
        ),
    ]
