# Generated by Django 3.2.7 on 2021-11-22 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_auto_20211122_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_salida_materiaprima',
            name='codigo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.movimientos_almacen'),
        ),
        migrations.AlterField(
            model_name='ordenes_salida_materiaprima',
            name='empleado_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordenes_salida_materiaprima',
            name='proyecto_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.proyectos'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='estado_proyecto',
            field=models.CharField(choices=[('Act', 'Activo'), ('Ter', 'Terminado'), ('Na', 'No Asignado')], default='Na', max_length=12),
        ),
    ]
