# Generated by Django 3.2.7 on 2021-11-22 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_auto_20211122_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facturas',
        ),
        migrations.RemoveField(
            model_name='materia_prima',
            name='Almacen_cod_movimiento',
        ),
        migrations.RemoveField(
            model_name='materia_prima',
            name='cantidad_almacen',
        ),
        migrations.RemoveField(
            model_name='materia_prima',
            name='cantidad_minima',
        ),
        migrations.RemoveField(
            model_name='materia_prima',
            name='orden_pedido',
        ),
        migrations.RemoveField(
            model_name='materia_prima',
            name='seccion_ubicacion_material',
        ),
        migrations.RemoveField(
            model_name='ordenes_salida_materiaprima',
            name='codigo_movimiento',
        ),
        migrations.AddField(
            model_name='materia_prima',
            name='cod_movimiento_ingreso',
            field=models.ManyToManyField(to='inventarios.Movimientos_Almacen'),
        ),
        migrations.AddField(
            model_name='materia_prima',
            name='numero_factura_compra',
            field=models.CharField(default='0000000000', max_length=100),
        ),
        migrations.AddField(
            model_name='ordenes_pedido_materiaprima',
            name='empleado_solicitante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenes_salida_materiaprima',
            name='cod_movimiento_salida',
            field=models.ManyToManyField(to='inventarios.Movimientos_Almacen'),
        ),
        migrations.AlterField(
            model_name='contratistas',
            name='proyecto_asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.proyectos'),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='Proveedores_cod_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.proveedores'),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='unidad_de_medida',
            field=models.CharField(choices=[('Un', 'Unidad'), ('Lb', 'Libras'), ('Kg', 'Kilogramos'), ('In', 'Pulgadas'), ('Cm', 'Centimetros'), ('Mt', 'Metros'), ('Pi', 'Pies'), ('M2', 'Metros Cuadrados'), ('M3', 'Metros Cubicos'), ('Lt', 'Litros'), ('Ml', 'Mililitros'), ('Gl', 'Galones'), ('1/16', '1/16 de Galón'), ('1/8', '1/8 de Galón'), ('1/4', '1/4 de Galón'), ('1/2', '1/2 Galón')], default='Un', max_length=15),
        ),
        migrations.AlterField(
            model_name='ordenes_pedido_materiaprima',
            name='codigo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.materia_prima'),
        ),
        migrations.AlterField(
            model_name='ordenes_pedido_materiaprima',
            name='proveedores_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.proveedores'),
        ),
    ]
