# Generated by Django 3.2.7 on 2021-11-22 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_auto_20211122_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_pedido_materiaprima',
            name='empleado_solicitante',
            field=models.ForeignKey(default='-------', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
