# Generated by Django 3.2.7 on 2021-11-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0009_alter_ordenes_pedido_materiaprima_empleado_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia_prima',
            name='cantidad',
            field=models.IntegerField(default='1'),
        ),
    ]
