# Generated by Django 3.2.7 on 2021-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0010_materia_prima_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia_prima',
            name='marca',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
