# Generated by Django 3.2.7 on 2021-11-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0011_materia_prima_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes_pedido_materiaprima',
            name='proveedores_codigo',
        ),
    ]
