# Generated by Django 3.2.7 on 2021-11-24 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0012_remove_ordenes_pedido_materiaprima_proveedores_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia_prima',
            name='unidad_de_medida',
            field=models.CharField(choices=[('Un', 'Unidad'), ('Lb', 'Libras'), ('Kg', 'Kilogrmos'), ('In', 'Pulgadas'), ('Cm', 'Centimetros'), ('Mt', 'Metros'), ('Pi', 'Pies'), ('M2', 'Metros Cuadrados'), ('M3', 'Metros Cúbicos'), ('Lt', 'Litros'), ('Ml', 'Mililitros'), ('Gl', 'Galones'), ('1/16', '1/16 de Galón'), ('1/8', '1/8 de Galón'), ('1/4', '1/4 de Galón'), ('1/2', '1/2 Galón')], default='Un', max_length=15),
        ),
        migrations.AlterField(
            model_name='ordenes_salida_materiaprima',
            name='codigo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.materia_prima'),
        ),
    ]
