# Generated by Django 3.2.7 on 2021-11-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0013_auto_20211123_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='nombre_proyecto',
            field=models.CharField(default='--------', max_length=100),
        ),
    ]
