# Generated by Django 3.2.7 on 2021-11-24 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0014_proyectos_nombre_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratistas',
            name='proyecto_asignacion',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='contratista_asignado',
            field=models.ForeignKey(default='-------', on_delete=django.db.models.deletion.CASCADE, to='inventarios.contratistas'),
        ),
    ]
