# Generated by Django 3.2.7 on 2021-11-24 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0020_auto_20211123_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='contratistas',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='contratistas',
            field=models.ForeignKey(default='-------', on_delete=django.db.models.deletion.CASCADE, to='inventarios.contratistas'),
        ),
    ]
