# Generated by Django 3.2.7 on 2021-11-24 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0021_auto_20211123_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='contratistas',
            field=models.ForeignKey(default='00000000', on_delete=django.db.models.deletion.CASCADE, to='inventarios.contratistas'),
        ),
    ]
