# Generated by Django 3.2.7 on 2021-11-24 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0022_alter_proyectos_contratistas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='contratistas',
        ),
        migrations.AddField(
            model_name='contratistas',
            name='proyecto_asignacion',
            field=models.ForeignKey(default='00000000', on_delete=django.db.models.deletion.CASCADE, to='inventarios.proyectos'),
        ),
    ]
