# Generated by Django 3.2.7 on 2021-11-27 23:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('identificacion', models.BigIntegerField(default='0000000000')),
                ('cargo_empleado', models.CharField(choices=[('Gerente General', 'Director General'), ('Director Operacional', 'Director Operacional'), ('Almacenista', 'Almacenista'), ('Contratista', 'Contratista'), ('NA', 'No Asignado')], default='NA', max_length=50)),
                ('telefono_empleado', models.BigIntegerField(default='0000000000')),
                ('correo_empleado', models.EmailField(default='ejemplo@ejemplo.com', max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Materia_prima',
            fields=[
                ('codigo_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('numero_factura_compra', models.CharField(default='0000000000', max_length=100)),
                ('cantidad', models.IntegerField(default='1')),
                ('unidad_de_medida', models.CharField(choices=[('Un', 'Unidad'), ('Lb', 'Libras'), ('Kg', 'Kilogramos'), ('In', 'Pulgadas'), ('Cm', 'Centimetros'), ('Mt', 'Metros'), ('Pi', 'Pies'), ('M2', 'Metros Cuadrados'), ('M3', 'Metros Cubicos'), ('Lt', 'Litros'), ('Ml', 'Mililitros'), ('Gl', 'Galones'), ('1/16', '1/16 de Galón'), ('1/8', '1/8 de Galón'), ('1/4', '1/4 de Galón'), ('1/2', '1/2 Galón')], default='Un', max_length=15)),
                ('precio', models.IntegerField()),
                ('marca', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos_Almacen',
            fields=[
                ('cod_movimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('En', 'Entrada'), ('Sa', 'Salida'), ('Na', 'Sin Asignar Aún')], default='Na', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('codigo_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('direccion_proveedor', models.CharField(max_length=100)),
                ('barrio_proveedor', models.CharField(max_length=50)),
                ('ciudad_proveedor', models.CharField(max_length=50)),
                ('telefono_proveedor', models.IntegerField()),
                ('website_proveedor', models.CharField(max_length=50)),
                ('email', models.EmailField(default='ejemplo@ejemplo.com', max_length=254)),
                ('maneja_credito', models.CharField(choices=[('Si', 'Si Maneja Crédito'), ('No', 'No Ofrece Crédito')], default='No', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('codigo_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('direccion_proyecto', models.CharField(max_length=100)),
                ('descripcion_proyecto', models.CharField(max_length=200)),
                ('estado_proyecto', models.CharField(choices=[('Act', 'Activo'), ('Ter', 'Terminado'), ('Na', 'No Asignado')], default='Na', max_length=12)),
                ('empleado_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ordenes_salida_materiaprima',
            fields=[
                ('codigo_orden_salida', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_entregada', models.IntegerField()),
                ('fecha_entrega_materiaprima', models.DateTimeField(auto_now_add=True)),
                ('cod_movimiento_salida', models.ForeignKey(default='00000000', on_delete=django.db.models.deletion.CASCADE, to='operaciones.movimientos_almacen')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.materia_prima')),
                ('empleado_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='ordenes_pedido_materiaprima',
            fields=[
                ('codigo_orden_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_pedida', models.IntegerField()),
                ('fecha_orden_pedido', models.DateTimeField(auto_now_add=True)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.materia_prima')),
                ('empleado_solicitante', models.ForeignKey(default='-------', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='materia_prima',
            name='Proveedores_cod_proveedor',
            field=models.ManyToManyField(to='operaciones.Proveedores'),
        ),
        migrations.AddField(
            model_name='materia_prima',
            name='cod_movimiento_ingreso',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='operaciones.movimientos_almacen'),
        ),
        migrations.CreateModel(
            name='Contratistas',
            fields=[
                ('codigo_contratista', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_contratista', models.CharField(max_length=50)),
                ('apellido_contratista', models.CharField(default='', max_length=50)),
                ('identificacion', models.IntegerField(default='000000000')),
                ('direccion_contratista', models.CharField(max_length=100)),
                ('correo_contratista', models.EmailField(default='ejemplo@ejemplo.com', max_length=254)),
                ('telefono_contratista', models.IntegerField()),
                ('especialidad_contratista', models.CharField(max_length=50)),
                ('proyecto_asignacion', models.ManyToManyField(to='operaciones.Proyectos')),
            ],
        ),
    ]
