# Generated by Django 3.2.7 on 2021-11-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratistas',
            name='identificacion',
            field=models.CharField(default='000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='contratistas',
            name='telefono_contratista',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion_proyecto',
            field=models.TextField(),
        ),
    ]
