# Generated by Django 3.2.7 on 2021-12-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_auto_20211130_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia_prima',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='materia_prima',
            name='numero_factura_compra',
        ),
        migrations.CreateModel(
            name='EntradasAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura_compra', models.CharField(default='0000000000', max_length=100)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default='1')),
                ('codigo_material', models.ManyToManyField(to='operaciones.Materia_prima')),
            ],
        ),
    ]
