# Generated by Django 3.2.7 on 2021-11-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_auto_20211130_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratistas',
            name='identificacion',
            field=models.IntegerField(default='000000000'),
        ),
        migrations.AlterField(
            model_name='contratistas',
            name='telefono_contratista',
            field=models.IntegerField(),
        ),
    ]
